### ISSUE TITLE
Add support for Neo4j 5

### ISSUE THREAD

**Issue by vickyyat** [marianozunino/morpheus#15]
This tool is great but please make it work for Neo4j 5 version.

**Comment by marianozunino** [comment]
Hey @vickyyat thanks for the feedback. Seems like neo4j 5 made some changes to Cypher. 

I'll update the project as soon as I can. 

Mind to share how are you using it? as an NPM script, or grammatically via NestJs?

**Comment by vickyyat** [comment]
Thanks! My team currently uses NPM script but we will be migrating to NestJS very soon.

**Comment by marianozunino** [comment]
https://github.com/marianozunino/morpheus/releases/tag/v2.4.0
