### ISSUE TITLE
How do you create migrations in nestjs?

### ISSUE THREAD

**Issue by KMV-7** [marianozunino/morpheus#16]
Hey, 
First of, thanks for the tool.
I have followed the instructions and created the morpheus config in forRoorAsync. Then my Nest app starts and tries to run migrations, which is expected. It also creates the __Neo4jMigration node of version BASELINE which is also expected.
However, I can't create migrations with `npm run morpheus init` because it says that there is no .morpheus.json but I don't need .morpheus.json because I already have my config in main.ts. 
Also, if I try to create the migration manually in src/neo4j/migrations such as src/neo4j/migrations/V1_0_0__test.cypher it still says "Database up to date" when starting without performing the migrations.
I ve gone through the code in the repo and I still seem unable to do it.
Any advices?

**Comment by marianozunino** [comment]
Hey @KMV-7 , thanks for the feedback. 

Here's an example using nestjs: https://github.com/marianozunino/example-morpheus-neo4j

If you want to run migrations with a npm script, then you **do need** a `.morpheus.json` file, but if you want to leave the migrations to be handled by Nestjs then you do not need it.

**Comment by marianozunino** [comment]
Also, fixed a bug that when using just Nestjs the migrations folder wasn't being created.
 
https://github.com/marianozunino/morpheus/releases/tag/v2.3.3
