### ISSUE TITLE
[Question] Neo4j Aura support

### ISSUE THREAD

**Issue by Nimphal** [marianozunino/morpheus#18]
Hello! We are trying to run migrations using this library against a Neo4j Aura instance and have come up against an error:
```Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1675172819699, routers=[], readers=[], writers=[]]```

We've been digging around and doing all sorts of configuration changes, but haven't been successful at making it work. Would you expect it to work without a hitch? We're using `neo4j+s` in the url and the scheme is `neo4j` (though we've tried multiple combinations). We have validated that the db is up and that the credentials are correct.

Any help greatly appreciated!

**Comment by marianozunino** [comment]
@Nimphal I just created a new Aura instance and I had no issues. 

Here's my `config.json` file:

```
{
  "host": "b2a45683.databases.neo4j.io",
  "port": 7687,
  "username": "neo4j",
  "password": "<password>",
  "scheme": "neo4j+s",
  "migrationsPath": "neo4j/migrations"
}
```

![image](https://user-images.githubusercontent.com/6627528/215790814-df449051-aa75-4b83-bbb6-2440e1050c08.png)


Let me know if that does still not work in your end.

**Comment by Nimphal** [comment]
OMG, you are my favourite person today, thank you so much:
1. for the quick response
2. for solving our issue
If anyone else comes by this, we were including the `neo4j+s` in the host variable, seeing the example above we removed that and it worked like a charm.
