### ISSUE TITLE
Migrations over version 10+ are not triggered

### ISSUE THREAD

**Issue by kacperhes** [marianozunino/morpheus#29]
If migration number is 10 or more the migration is not triggered at all. Below are the screenshots of the behaviour from command line as well as neo4j playground:

 1. Creating new migration which automatically asigns number 10 (correct behaviour): 
<img width="624" alt="Screen Shot 2023-05-16 at 15 22 27" src="https://github.com/marianozunino/morpheus/assets/23403467/90d9208c-3070-46e5-9ee6-c15f7e6e6d2c">

2. Running migrations (incorrect, should run migration 10 as well):
<img width="286" alt="Screen Shot 2023-05-16 at 15 22 58" src="https://github.com/marianozunino/morpheus/assets/23403467/f93a3ea4-d20e-44f0-b717-06f825da846c">

3.  Database after migration (incorrect, should have node V10_0_0):
![Screen Shot 2023-05-16 at 15 23 11](https://github.com/marianozunino/morpheus/assets/23403467/288f95db-2d5d-4a96-b3e4-c94092aa33f6)

**Comment by marianozunino** [comment]
@kacperhes may I ask what version of morpheus are you using? I just created an aura instance to test this out and I got the following result:

![imagen](https://github.com/marianozunino/morpheus/assets/6627528/7a095a57-1d28-473a-a851-7655ba2f433b)

**Comment by kacperhes** [comment]
@marianozunino 
^2.4.0

**Comment by marianozunino** [comment]
Related to this bug: https://github.com/marianozunino/morpheus/issues/25
Got fixed in the version 3.0.2

**Comment by kacperhes** [comment]
I was able to fix it locally. Thank you for quick response!
