### ISSUE TITLE
nestJS required

### ISSUE THREAD

**Issue by jroith** [marianozunino/morpheus#40]
I'm getting an error "Error: Cannot find module '@nestjs/common'". Is this intentional? Does morpheus have a peer dependency on nestJS?

**Comment by marianozunino** [comment]
[Reference](https://github.com/marianozunino/morpheus/issues/36#issuecomment-1875396330)

I haven't had any time to finish the "split" of the cli/nestjs.

**Comment by marianozunino** [comment]
Update:

I finally was able to move to a mono repo, right now is sitting under the [monorepo](https://github.com/marianozunino/morpheus/tree/monorepo) branch. Still need to migrate tests (sigh), and the nestjs module (easy)
